name: EdibleHearts
version: 3.1
main: me.cageydinosaur.addHearts.Main
api-version: 1.18
commands:
  heart:
    usage: /heart
    description: Command for changing amount of hearts of a player. Enter it to see usage

permissions:
  heart:
    default: true
    children:
      heart.use:
        default: true
      heart.20:
        default: true

  heart.reload:
    default: op
  heart.add:
    default: op
  heart.remove:
    default: op